openapi: 3.0.0
info:
  title: Book Order Service API
  version: 1.0.0
  description: API for placing book orders
servers:
  - url: http://localhost:5000
paths:
  /POST/api/books/orders:
    post:
      summary: Place book order
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                book_id:
                  type: integer
                quantity_ordered:
                  type: integer
              required:
                - book_id
                - quantity_ordered
      responses:
        '201':
          description: Order placed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    OrderResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
