openapi: 3.0.0
info:
  title: Book Inventory Service API
  version: 1.0.0
paths:
  /api/books/inventory:
    get:
      summary: Get book inventory by book ID or retrieve all inventories
      parameters:
        - in: query
          name: book_id
          schema:
            type: integer
          description: ID of the book inventory to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Inventory'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Inventory'
  /api/books/inventory/update:
    post:
      summary: Update book inventory by book ID
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateInventoryRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Inventory:
      type: object
      properties:
        book_id:
          type: integer
        quantity:
          type: integer
        available_quantity:
          type: integer
    UpdateInventoryRequest:
      type: object
      properties:
        book_id:
          type: integer
        quantity:
          type: integer
 