openapi: 3.0.0
info:
  title: Book Inventory Service API
  version: 1.0.0
  description: API for managing book inventories
servers:
  - url: http://localhost:5000
paths:
  /GET/api/books/inventory:
    get:
      summary: Get book inventory
      parameters:
        - name: book_id
          in: query
          description: ID of the book
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '404':
          description: Inventory not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    /UPDATE/api/books/inventory:
    post:
      summary: Update book inventory
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                book_id:
                  type: integer
                quantity:
                  type: integer
              required:
                - book_id
                - quantity
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Inventory:
      type: object
      properties:
        id:
          type: integer
        book_id:
          type: integer
        quantity:
          type: integer
        available_quantity:
          type: integer
      required:
        - id
        - book_id
        - quantity
        - available_quantity
